# The Site Configuration
theme: jekyll-theme-chirpy
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en
prefer_datetime_locale:
timezone: Europe/Madrid

title: Carlos Sanchez # the main title
tagline: Software Engineer | HomeLab # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Carlos Sanchez Home - Documentation and More

url: "https://carlossanchez01.github.io"

github:
  username: carlossanchez01 # change to your github username

twitter:
  username: carlossanch01 # change to your twitter username

social:
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: carlossanchez01
  # email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/carlossanchez01 # change to your github homepage
    # - https://ive/twitter # change to your twitter homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

analytics:
  google:
    id: # Fill with your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID

img_cdn:
avatar: https://avatars.githubusercontent.com/u/29235710?v=4
# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active: giscus # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: carlossanchez01/carlossanchez01.github.io
    repo_id:
    category: Comments
    category_id: DIC_kwDODy-1C84CSN7z
    mapping: pathname # optional, default to 'pathname'
    input_position: bottom # optional, default to 'bottom'
    lang: en # optional, default to the value of `site.lang`
    reactions_enabled: 1

assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: false # the option for PWA feature (installable)
  cache:
    enabled: false # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    deny_paths:

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - archive_old
  - template
  - reference_files
  - kubernetes
  - Dockerfile

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
